
/*******************************************************************************
* generated by lcd-image-converter rev.c6da9ce from 2018-02-11 00:03:45 +0500
* font
* filename: D:/googleDrive/Projects/solderstation/avr/solderstatin/Font8.xml
* name: Font8
* family: Small Fonts
* size: 8
* style: Normal
* included characters: 0123456789- %
* antialiasing: no
* type: proportional
* encoding: windows-1251
* unicode bom: no
*
* preset name: WG12864
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
typedef struct _tPropSymbol
{
	uint8_t Symbol;								//Symbol code
	uint8_t Width;								//bit for FontWidthType = PROP
} sPROP_SYMBOL;

typedef struct _tFont
{    
  const uint8_t *table;							//draw
  uint16_t Width;								//fixed font only
  uint16_t Height;								
  const uint8_t tableSymbolSize;				//if null then table is full ascii table
  const uint8_t *tableSymbol;					
  const struct sPROP_SYMBOL *tableSymbol;		//if tableSymbolSize is not null then table symbol
  const enum FontWidthType FontType;
} sFONT;
*/

#include "fonts.h"
#include <avr/pgmspace.h>


const uint8_t FontFont8_Table [] PROGMEM = 
{

    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙█
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙██
    // ∙∙∙██
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x4c, 
    0x2c, 
    0xd0, 
    0xc8, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙██
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x20, 
    0x20, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙█
    // ∙█∙∙█
    // ∙█∙∙█
    // ∙█∙∙█
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x78, 
    0x84, 
    0x84, 
    0x78, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙
    // ∙∙∙
    // ∙∙█
    // ∙██
    // ∙∙█
    // ∙∙█
    // ∙∙█
    // ∙∙█
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x08, 
    0xfc, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙█
    // ∙∙∙∙█
    // ∙∙██∙
    // ∙█∙∙∙
    // ∙████
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0xc8, 
    0xa4, 
    0xa4, 
    0x98, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙█
    // ∙∙∙█∙
    // ∙∙∙∙█
    // ∙█∙∙█
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x48, 
    0x84, 
    0x94, 
    0x68, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ∙∙██∙
    // ∙∙██∙
    // ∙█∙█∙
    // ∙████
    // ∙∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x60, 
    0x58, 
    0xfc, 
    0x40, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙
    // ∙∙∙∙
    // ∙███
    // ∙█∙∙
    // ∙██∙
    // ∙∙∙█
    // ∙∙∙█
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 
    0x9c, 
    0x94, 
    0x64, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙∙
    // ∙███∙
    // ∙█∙∙█
    // ∙█∙∙█
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x78, 
    0x94, 
    0x94, 
    0x60, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙
    // ∙∙∙∙
    // ∙███
    // ∙∙∙█
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 
    0x04, 
    0xf4, 
    0x0c, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙█
    // ∙∙██∙
    // ∙█∙∙█
    // ∙█∙∙█
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x68, 
    0x94, 
    0x94, 
    0x68, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00,

    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙█
    // ∙∙███
    // ∙∙∙∙█
    // ∙█∙∙█
    // ∙∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 
    0x48, 
    0x94, 
    0x94, 
    0x78, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00

};

const sPROP_SYMBOL FontFont8_NumSym [13] PROGMEM = 
{
	{0x20, 2},	/* */
	{0x25, 5},	/*%*/
	{0x2d, 3},	/*-*/
	{0x30, 5},	/*0*/
	{0x31, 3},	/*1*/
	{0x32, 5},	/*2*/
	{0x33, 5},	/*3*/
	{0x34, 5},	/*4*/
	{0x35, 4},	/*5*/
	{0x36, 5},	/*6*/
	{0x37, 4},	/*7*/
	{0x38, 5},	/*8*/
	{0x39, 5}	/*9*/

};


sFONT Font8 = {
  FontFont8_Table,
  5, /* Width */
  10, /* Height */
  13, /*symbol count*/
  FontFont8_NumSym, /*symbol list*/
  proportional
};


